### ISSUE TITLE
A SMBUS problem

### ISSUE THREAD

**Issue by bsimmo** [pimoroni/rainbow-hat#14]
Sorry but this will be a bit of an open issue.

At a recent PiJam in Hull we could not get the code to install on any of the fresh images of Raspbian. (It may be a Stretch problem)
I do not know if these had been updated or were still a default September 2017 stretch image.
But on trying to install etc.
An issue came up with Python3 and smbus error (doesn't have one of the calls iirc.)

Sorry for the vague issues.
I believe you already know it as Tanya was there ;-)

Just thought I would see if it was/needs fixing.

I don't have a hat to see if I can help with the issue.

**Comment by Gadgetoid** [comment]
I think this is an issue with one of the alternate SMBUS libraries being installed in place of *actual* SMBUS. I don't know which library, or how this is happening, but I've started setting up to look into this, because you're far from the first person to report it.
