### ISSUE TITLE
Problems with install script

### ISSUE THREAD

**Issue by dstinebaugh** [pimoroni/rainbow-hat#4]
Issues with installing spidev and smbus for python3, as well as both rainbowhat apt call's failed along with python2 library. 

Output shared via pastebin  here:
http://pastebin.com/8eT5y6FL

**Comment by RogueM** [comment]
well, it sounds like your APT indexes were broken before you start... there is not much the installer can do in that case, save trying to fix your install (which is likely not trivial).

Try running the following manually, then try again the rainbowhat script:

`sudo apt-get -f install`

... if that does not work afterwards then there is some other issue with your APT sources, it certainly should not happen on Raspbian.
