### ISSUE TITLE
rainbowhat.display.print_float still shows thousands when value drops below 1000.

### ISSUE THREAD

**Issue by cjmair** [pimoroni/rainbow-hat#5]
When using  rainbowhat.display.print_float( rainbowhat.weather.pressure() / 100 ) to display the air pressure in Hectopascals if the pressure drops below 1000, i.e. goes from 1001 to 999 the 1 in the first digit is still displayed e.g. 1999 is displayed rather than 999.

Colin

**Comment by Gadgetoid** [comment]
Although it violates the principle of least surprise, this is by design. You should explicitly `clear()` the display before displaying to it again. This is so you can do things like:

```
rainbowhat.display.print_number_str('12', justify_right=False)
rainbowhat.display.print_number_str('99', justify_right=True)
rainbowhat.display.show()
```

Under the hood, each helper function for drawing numbers etc just calls `set_digit` and `set_decimal`.

**Comment by cjmair** [comment]
Ok, thank you.
